import { Exercise } from '../types'

export const EXERCISES: Exercise[] = [
  // ─── Workout A ────────────────────────────────────────────────────────────
  {
    id: 'lat_pulldown',
    name_ru: 'Тяга верхнего блока',
    name_en: 'Lat Pulldown',
    muscle_primary: 'Широчайшие',
    is_compound: true,
    increment_kg: 2.5,
    tempo: '3-1-2',
    workout_slot: 'A',
    exercise_order: 1,
    sets: 4,
    reps: '10-12',
    muscle_emoji: '🏋️',
    tips_ru: '🔑 V-тейп секрет: УЗКИЙ хват — локти вдоль тела. Широкий хват качает трапеции, НЕ широчайшие. Тяни лопатки ВНИЗ перед стартом движения.',
    gifUrl: 'https://static.exercisedb.dev/media/rkg41Fb.gif',
    instagramUrl: 'https://www.instagram.com/reel/DVbb-gZjk0G/',
    alternatives: ['pull_over', 'rocky_pulldown', 'assisted_pullup']
  },
  {
    id: 'chest_press',
    name_ru: 'Жим в тренажёре',
    name_en: 'Chest Press Machine',
    muscle_primary: 'Грудь',
    is_compound: true,
    increment_kg: 5,
    tempo: '3-1-2',
    workout_slot: 'A',
    exercise_order: 2,
    sets: 4,
    reps: '10-12',
    muscle_emoji: '💪',
    tips_ru: 'Лопатки сведены и опущены. Не отрывай спину от спинки. Темп 3-1-2 обязателен.',
    gifUrl: 'https://static.exercisedb.dev/media/wDN97Ca.gif',
    alternatives: ['incline_pec_fly', 'cable_fly', 'push_up']
  },
  {
    id: 'shoulder_press',
    name_ru: 'Жим плеч',
    name_en: 'Shoulder Press Machine',
    muscle_primary: 'Дельты',
    is_compound: true,
    increment_kg: 2.5,
    tempo: '3-1-2',
    workout_slot: 'A',
    exercise_order: 3,
    sets: 4,
    reps: '10-12',
    muscle_emoji: '🤲',
    tips_ru: 'Не блокируй локти в верхней точке. Опускай до угла 90° в локте — не ниже, чтобы беречь плечи.',
    gifUrl: 'https://static.exercisedb.dev/media/67n3r98.gif',
    instagramUrl: 'https://www.instagram.com/reel/DWAUGaalCyz/',
    alternatives: ['cable_lateral_raise', 'dumbbell_press', 'arnold_press']
  },
  {
    id: 'incline_pec_fly',
    name_ru: 'Разводка (наклон)',
    name_en: 'Incline Pec Deck',
    muscle_primary: 'Верхняя грудь',
    is_compound: false,
    increment_kg: 2.5,
    tempo: '3-1-2',
    workout_slot: 'A',
    exercise_order: 4,
    sets: 3,
    reps: '12',
    muscle_emoji: '🦅',
    tips_ru: 'Контролируй движение на всём диапазоне. Чувствуй растяжение в верхней части груди. Не своди руки слишком резко.',
    gifUrl: 'https://static.exercisedb.dev/media/vi8EhoE.gif',
    alternatives: ['chest_press', 'cable_fly']
  },
  {
    id: 'cable_lateral_raise',
    name_ru: 'Боковые разводки (кабель)',
    name_en: 'Cable Lateral Raise',
    muscle_primary: 'Боковые дельты',
    is_compound: false,
    increment_kg: 2.5,
    tempo: '2-0-2',
    workout_slot: 'A',
    exercise_order: 5,
    sets: 3,
    reps: '15',
    muscle_emoji: '↔️',
    tips_ru: '🔑 V-тейп секрет: боковые дельты дают ШИРИНУ плечам. Держи небольшой наклон вперёд, локоть чуть согнут. Кабель = равномерная нагрузка по всей траектории.',
    gifUrl: 'https://static.exercisedb.dev/media/myJeTAe.gif',
    instagramUrl: 'https://www.instagram.com/reel/DV6OAHpCXMc/',
    alternatives: ['shoulder_press', 'dumbbell_lateral']
  },
  {
    id: 'leg_press',
    name_ru: 'Жим ногами',
    name_en: 'Leg Press',
    muscle_primary: 'Квадрицепсы',
    is_compound: true,
    increment_kg: 5,
    tempo: '3-1-2',
    workout_slot: 'A',
    exercise_order: 6,
    sets: 4,
    reps: '10-12',
    muscle_emoji: '🦵',
    tips_ru: 'Не блокируй колени в верхней точке! Стопы на ширине плеч, пятки давят в платформу. Поясница прижата.',
    gifUrl: 'https://static.exercisedb.dev/media/10Z2DXU.gif',
    instagramUrl: 'https://www.instagram.com/reel/DV4mQyviG46/',
    alternatives: ['squat', 'split_squat', 'hack_squat']
  },
  {
    id: 'seated_leg_curl',
    name_ru: 'Сгибание ног сидя',
    name_en: 'Seated Leg Curl',
    muscle_primary: 'Бицепс бедра',
    is_compound: false,
    increment_kg: 2.5,
    tempo: '3-1-2',
    workout_slot: 'A',
    exercise_order: 7,
    sets: 3,
    reps: '12',
    muscle_emoji: '🦿',
    tips_ru: 'Полный диапазон движения. Не дёргай — контролируй обратную фазу 2 секунды. Стопы параллельны или чуть развёрнуты внутрь.',
    gifUrl: 'https://static.exercisedb.dev/media/Zg3XY7P.gif',
    alternatives: ['leg_extension', 'rdl']
  },
  {
    id: 'abdominal_crunch',
    name_ru: 'Скручивания на пресс',
    name_en: 'Ab Crunch Machine',
    muscle_primary: 'Пресс',
    is_compound: false,
    increment_kg: 0,
    tempo: 'свободный',
    workout_slot: 'A',
    exercise_order: 8,
    sets: 3,
    reps: '15',
    muscle_emoji: '🎯',
    tips_ru: 'Фокус на сжатии мышц пресса, а не на подъёме тела. Руки за ушами, не тяни шею. Выдох на сжатии.',
    gifUrl: 'https://static.exercisedb.dev/media/TFqbd8t.gif',
    alternatives: []
  },
  {
    id: 'trap_shrug',
    name_ru: 'Шраги (трапеции)',
    name_en: 'Dumbbell Shrugs',
    muscle_primary: 'Трапеция',
    is_compound: false,
    increment_kg: 2.5,
    tempo: '2-1-2',
    workout_slot: 'A',
    exercise_order: 9,
    sets: 3,
    reps: '15',
    muscle_emoji: '🦬',
    tips_ru: '🔑 V-тейп секрет: развитые трапеции придают мощный вид сзади. Подними плечи максимально вверх, задержи 1 сек на пике. Не вращай плечами — только вертикаль.',
    gifUrl: 'https://static.exercisedb.dev/media/3GkSvR2.gif',
    instagramUrl: 'https://www.instagram.com/reel/DV4fXwtFJgo/',
    alternatives: []
  },

  // ─── Workout B ────────────────────────────────────────────────────────────
  {
    id: 'pull_over',
    name_ru: 'Пуловер',
    name_en: 'Cable Pullover',
    muscle_primary: 'Широчайшие',
    is_compound: true,
    increment_kg: 2.5,
    tempo: '3-1-2',
    workout_slot: 'B',
    exercise_order: 1,
    sets: 4,
    reps: '10-12',
    muscle_emoji: '🏋️',
    tips_ru: 'Растяни широчайшие в верхней точке — пауза 1 сек. Пуловер уникален: нагружает лат в растянутом положении = максимум роста.',
    gifUrl: 'https://static.exercisedb.dev/media/vi8EhoE.gif',
    alternatives: ['lat_pulldown', 'straight_arm_pulldown']
  },
  {
    id: 'linear_back_row',
    name_ru: 'Тяга горизонтального блока',
    name_en: 'Seated Cable Row',
    muscle_primary: 'Спина (толщина)',
    is_compound: true,
    increment_kg: 2.5,
    tempo: '3-1-2',
    workout_slot: 'B',
    exercise_order: 2,
    sets: 4,
    reps: '10-12',
    muscle_emoji: '🔗',
    tips_ru: 'Тяни к поясу, локти вдоль тела. Сводим лопатки — не горбись. Корпус прямой, без раскачки.',
    gifUrl: 'https://static.exercisedb.dev/media/7I6LNUG.gif',
    alternatives: ['low_row', 'cable_row', 'dumbbell_row']
  },
  {
    id: 'shoulder_press_b',
    name_ru: 'Жим плеч (2й раз)',
    name_en: 'Shoulder Press Machine',
    muscle_primary: 'Дельты',
    is_compound: true,
    increment_kg: 2.5,
    tempo: '3-1-2',
    workout_slot: 'B',
    exercise_order: 3,
    sets: 3,
    reps: '12',
    muscle_emoji: '🤲',
    tips_ru: 'Не блокируй локти в верхней точке. Опускай до угла 90° в локте — не ниже, чтобы беречь плечи.',
    gifUrl: 'https://static.exercisedb.dev/media/67n3r98.gif',
    instagramUrl: 'https://www.instagram.com/reel/DWAUGaalCyz/',
    alternatives: ['cable_lateral_raise', 'dumbbell_press', 'arnold_press']
  },
  {
    id: 'cable_lateral_raise_b',
    name_ru: 'Боковые разводки (2й раз)',
    name_en: 'Cable Lateral Raise',
    muscle_primary: 'Боковые дельты',
    is_compound: false,
    increment_kg: 2.5,
    tempo: '2-0-2',
    workout_slot: 'B',
    exercise_order: 4,
    sets: 3,
    reps: '15',
    muscle_emoji: '↔️',
    tips_ru: '🔑 V-тейп секрет: боковые дельты дают ШИРИНУ плечам. Держи небольшой наклон вперёд, локоть чуть согнут. Кабель = равномерная нагрузка по всей траектории.',
    gifUrl: 'https://static.exercisedb.dev/media/myJeTAe.gif',
    instagramUrl: 'https://www.instagram.com/reel/DV6OAHpCXMc/',
    alternatives: ['shoulder_press', 'dumbbell_lateral']
  },
  {
    id: 'leg_extension',
    name_ru: 'Разгибание ног',
    name_en: 'Leg Extension',
    muscle_primary: 'Квадрицепсы',
    is_compound: false,
    increment_kg: 2.5,
    tempo: '3-1-2',
    workout_slot: 'B',
    exercise_order: 5,
    sets: 4,
    reps: '12',
    muscle_emoji: '🦵',
    tips_ru: 'Пик-сокращение в верхней точке — задержи 1 сек. Спина прижата к спинке. Не используй инерцию.',
    gifUrl: 'https://static.exercisedb.dev/media/my33uHU.gif',
    alternatives: ['leg_press', 'wall_sit']
  },
  {
    id: 'ham_curl',
    name_ru: 'Сгибание ног (одна нога)',
    name_en: 'Lying Leg Curl',
    muscle_primary: 'Бицепс бедра',
    is_compound: false,
    increment_kg: 2.5,
    tempo: '3-1-2',
    workout_slot: 'B',
    exercise_order: 6,
    sets: 3,
    reps: '12',
    muscle_emoji: '🦿',
    tips_ru: 'Полный диапазон — полное разгибание внизу. Таз не должен подниматься. Фокус на растяжении бицепса бедра.',
    gifUrl: 'https://static.exercisedb.dev/media/Zg3XY7P.gif',
    alternatives: ['seated_leg_curl', 'rdl']
  },
  {
    id: 'biceps_curl',
    name_ru: 'Сгибание бицепс',
    name_en: 'Biceps Curl',
    muscle_primary: 'Бицепс',
    is_compound: false,
    increment_kg: 2.5,
    tempo: '3-1-2',
    workout_slot: 'B',
    exercise_order: 7,
    sets: 3,
    reps: '12',
    muscle_emoji: '💪',
    tips_ru: 'Локти зафиксированы у корпуса. В нижней точке полное разгибание — не срезай амплитуду.',
    gifUrl: 'https://static.exercisedb.dev/media/b4b6afT.gif',
    alternatives: ['hammer_curl', 'cable_curl']
  },
  {
    id: 'abdominal_crunch_b',
    name_ru: 'Скручивания на пресс',
    name_en: 'Ab Crunch Machine',
    muscle_primary: 'Пресс',
    is_compound: false,
    increment_kg: 0,
    tempo: 'свободный',
    workout_slot: 'B',
    exercise_order: 8,
    sets: 3,
    reps: '15',
    muscle_emoji: '🎯',
    tips_ru: 'Фокус на сжатии мышц пресса, а не на подъёме тела. Руки за ушами, не тяни шею. Выдох на сжатии.',
    gifUrl: 'https://static.exercisedb.dev/media/TFqbd8t.gif',
    alternatives: []
  },
  {
    id: 'cable_face_pull',
    name_ru: 'Тяга к лицу (кабель)',
    name_en: 'Cable Face Pull',
    muscle_primary: 'Задние дельты + Трапеция',
    is_compound: false,
    increment_kg: 2.5,
    tempo: '2-1-2',
    workout_slot: 'B',
    exercise_order: 9,
    sets: 3,
    reps: '15',
    muscle_emoji: '🎯',
    tips_ru: '🔑 V-тейп секрет: тяга к лицу — лучшее упражнение для здоровья плечей и объёма задних дельт. Тяни к ушам, локти выше плеч. Канатная рукоять, высокий блок.',
    gifUrl: 'https://static.exercisedb.dev/media/3GkSvR2.gif',
    alternatives: ['trap_shrug']
  }
]

export const getExercisesByWorkout = (workout: 'A' | 'B'): Exercise[] => {
  return EXERCISES
    .filter(e => e.workout_slot === workout)
    .sort((a, b) => a.exercise_order - b.exercise_order)
}

export const getExerciseById = (id: string): Exercise | undefined => {
  return EXERCISES.find(e => e.id === id)
}
