import { Exercise } from '../../types'

export const EXERCISES_A: Exercise[] = [
  {
    id: 'smith_incline_press',
    name_ru: 'Жим в Смите под углом 30°',
    name_en: 'Smith Machine Incline Press',
    muscle_primary: 'Грудь',
    muscle_emoji: '🏋️',
    is_compound: true,
    increment_kg: 2.5,
    tempo: '3-1-2',
    workout_slot: 'A',
    exercise_order: 1,
    tips_ru: 'Приоритет №1. Смит позволяет безопасно работать до отказа, что критично для гипертрофии верха груди.',
    sets: 3,
    reps: '8-10',
    instagramUrl: 'https://www.youtube.com/watch?v=VXaBbUYMfIs',
    alternatives: [],
  },
  {
    id: 'lat_pulldown_low_a',
    name_ru: 'Тяга блока на низ широчайших',
    name_en: 'Low Lat Cable Pulldown',
    muscle_primary: 'Спина',
    muscle_emoji: '🔝',
    is_compound: true,
    increment_kg: 2,
    tempo: '2-1-3',
    workout_slot: 'A',
    exercise_order: 2,
    tips_ru: 'В отказе — дополнительные частичные повторения в нижней части амплитуды. Узкий или однорукий хват усиливает растяжение.',
    sets: 4,
    reps: '10-15',
    instagramUrl: 'https://www.youtube.com/watch?v=6wzODtDJV_Q',
    alternatives: ['https://www.youtube.com/shorts/S-wUvzp0d_U', 'https://www.youtube.com/shorts/_NV8nNSaR0M', 'https://www.youtube.com/shorts/Snx3CAGxfXs'],
    video_landscape: true,
  },
  {
    id: 'seated_lateral_raise',
    name_ru: 'Махи гантелями в стороны сидя',
    name_en: 'Seated Dumbbell Lateral Raise',
    muscle_primary: 'Плечи',
    muscle_emoji: '🎯',
    is_compound: false,
    increment_kg: 1,
    tempo: '2-1-2',
    workout_slot: 'A',
    exercise_order: 3,
    tips_ru: 'Сидячая позиция исключает читинг. Работайте в «плоскости лопатки» (чуть перед собой).',
    sets: 4,
    reps: '15-20',
    instagramUrl: 'https://www.youtube.com/watch?v=Kl3LEzQ5Zqs',
    alternatives: [],
  },
  {
    id: 'hip_thrust',
    name_ru: 'Ягодичный мост со штангой',
    name_en: 'Barbell Hip Thrust',
    muscle_primary: 'Ягодицы',
    muscle_emoji: '🍑',
    is_compound: true,
    increment_kg: 5,
    tempo: '2-1-2',
    workout_slot: 'A',
    exercise_order: 4,
    tips_ru: 'Главное упражнение для формы ягодиц без перекачки бедер.',
    sets: 3,
    reps: '10-12',
    instagramUrl: 'https://www.youtube.com/watch?v=96uDbymTaHM',
    alternatives: ['https://www.youtube.com/watch?v=CvuVYMFd11g'],
  },
  {
    id: 'squat_a',
    name_ru: 'Приседания со штангой',
    name_en: 'Barbell Squat',
    muscle_primary: 'Ноги',
    muscle_emoji: '🦵',
    is_compound: true,
    increment_kg: 2.5,
    tempo: '3-1-2',
    workout_slot: 'A',
    exercise_order: 5,
    tips_ru: 'Следите за глубиной — бедро параллельно полу. Колени в направлении носков, спина нейтральная.',
    sets: 3,
    reps: '10-12',
    instagramUrl: 'https://www.youtube.com/watch?v=dW3zj79xfrc',
    alternatives: [],
  },
  {
    id: 'incline_bicep_curl',
    name_ru: 'Сгибания на наклонной скамье',
    name_en: 'Incline Dumbbell Curl',
    muscle_primary: 'Бицепс',
    muscle_emoji: '💪',
    is_compound: false,
    increment_kg: 1,
    tempo: '2-1-3',
    workout_slot: 'A',
    exercise_order: 6,
    tips_ru: 'Максимально растягивает длинную головку бицепса.',
    sets: 3,
    reps: '12-15',
    instagramUrl: 'https://www.youtube.com/shorts/uCUaRFlA9vE',
    alternatives: ['https://www.youtube.com/shorts/MPq3rlGjC1Y'],
  },
]
