import { Exercise } from '../../types'

export const EXERCISES_C: Exercise[] = [
  {
    id: 'lat_pulldown',
    name_ru: 'Тяга верхнего блока',
    name_en: 'Lat Pulldown',
    muscle_primary: 'Спина',
    muscle_emoji: '🔝',
    is_compound: true,
    increment_kg: 2,
    tempo: '2-1-3',
    workout_slot: 'C',
    exercise_order: 1,
    tips_ru: 'Хват широкий, наклон назад 20-30°. Тяни к верхней части груди, сводя лопатки. Контролируй подъём — 3 сек.',
    sets: 3,
    reps: '10-12',
    instagramUrl: 'https://www.instagram.com/reel/DVL0JI8DXHA/',
    alternatives: [],
  },
  {
    id: 'upright_row',
    name_ru: 'Тяга штанги к подбородку',
    name_en: 'Upright Row',
    muscle_primary: 'Плечи',
    muscle_emoji: '🎯',
    is_compound: true,
    increment_kg: 1,
    tempo: '2-1-2',
    workout_slot: 'C',
    exercise_order: 2,
    tips_ru: 'Хват узкий (чуть уже плеч). Тяни локти вверх и в стороны. Стоп у уровня подбородка. Не поднимай плечи к ушам.',
    sets: 3,
    reps: '10-15',
    instagramUrl: 'https://www.instagram.com/reel/DV3wsCnjUq0/',
    alternatives: [],
  },
  {
    id: 'cable_rear_delt_fly',
    name_ru: 'Разведения для задней дельты',
    name_en: 'Cable Rear Delt Fly',
    muscle_primary: 'Плечи',
    muscle_emoji: '🎯',
    is_compound: false,
    increment_kg: 1,
    tempo: '2-1-3',
    workout_slot: 'C',
    exercise_order: 3,
    tips_ru: 'Кабели скрест-вариант или гантели, наклон вперёд. Веди локти назад и в стороны, сводя лопатки. Фокус на задней дельте.',
    sets: 3,
    reps: '15-20',
    instagramUrl: 'https://www.instagram.com/reel/DVmCMK2jdrF/',
    alternatives: ['https://www.instagram.com/reel/DUpUEFLjV-9/'],
  },
  {
    id: 'lunges',
    name_ru: 'Выпады',
    name_en: 'Lunges',
    muscle_primary: 'Ноги',
    muscle_emoji: '🦵',
    is_compound: true,
    increment_kg: 2,
    tempo: '2-1-2',
    workout_slot: 'C',
    exercise_order: 4,
    tips_ru: 'Шаг вперёд, заднее колено почти касается пола. Переднее колено над носком. Держи корпус прямо. Чередуй ноги.',
    sets: 3,
    reps: '10-12',
    instagramUrl: 'https://www.instagram.com/reel/DVY01e-gU4u/',
    alternatives: ['https://www.instagram.com/reel/DVwi66liOve/'],
  },
  {
    id: 'leg_raise',
    name_ru: 'Подъёмы ног в висе',
    name_en: 'Leg Raise',
    muscle_primary: 'Пресс',
    muscle_emoji: '🔥',
    is_compound: false,
    increment_kg: 0,
    tempo: '2-1-3',
    workout_slot: 'C',
    exercise_order: 5,
    tips_ru: 'Вис на турнике. Поднимай прямые ноги до горизонтали или выше. Не раскачивайся. Опускай медленно — контроль.',
    sets: 3,
    reps: '12-20',
    instagramUrl: 'https://www.instagram.com/reel/DT54PEIlKNP/',
    alternatives: ['https://www.instagram.com/reel/DTlxpXslKSw/'],
  },
  {
    id: 'hammer_curl',
    name_ru: 'Молотковые сгибания',
    name_en: 'Hammer Curl',
    muscle_primary: 'Бицепс',
    muscle_emoji: '💪',
    is_compound: false,
    increment_kg: 1,
    tempo: '2-1-3',
    workout_slot: 'C',
    exercise_order: 6,
    tips_ru: 'Нейтральный хват (большой палец вверх). Локти у тела. Тренирует брахиалис и плечелучевую — даёт объём и толщину руки.',
    sets: 3,
    reps: '10-15',
    instagramUrl: 'https://www.instagram.com/reel/DVSR6FVgWd8/',
    alternatives: ['https://www.instagram.com/reel/DVjPOfeCG7p/'],
  },
]
