import { Exercise } from '../../types'

export const EXERCISES_B: Exercise[] = [
  {
    id: 'military_press',
    name_ru: 'Жим штанги стоя (Военный жим)',
    name_en: 'Military Press',
    muscle_primary: 'Плечи',
    muscle_emoji: '🎯',
    is_compound: true,
    increment_kg: 2,
    tempo: '2-1-2',
    workout_slot: 'B',
    exercise_order: 1,
    tips_ru: 'Штанга чуть ниже подбородка в старте. Жми вертикально вверх, убирая голову с пути. Кор напряжён — не прогибай поясницу.',
    sets: 3,
    reps: '8-12',
    instagramUrl: 'https://www.instagram.com/reel/DUrWSM5jv1_/',
    alternatives: [
      'https://www.instagram.com/reel/DToqx8-kijp/',
      'https://www.instagram.com/reel/DUUEdhkFNEv/',
    ],
  },
  {
    id: 'bent_over_row',
    name_ru: 'Тяга штанги в наклоне',
    name_en: 'Bent Over Row',
    muscle_primary: 'Спина',
    muscle_emoji: '🔝',
    is_compound: true,
    increment_kg: 2.5,
    tempo: '2-1-3',
    workout_slot: 'B',
    exercise_order: 2,
    tips_ru: 'Наклон 45°, спина нейтральная. Тяни штангу к нижней части живота, локти вдоль тела. Сожми лопатки в верхней точке.',
    sets: 3,
    reps: '8-12',
    instagramUrl: 'https://www.instagram.com/reel/DT8oOXdD1zS/',
    alternatives: [
      'https://www.instagram.com/reel/DT9eB_uExMS/',
      'https://www.instagram.com/reel/DURs7ZGmM-8/',
    ],
  },
  {
    id: 'rdl',
    name_ru: 'Румынская тяга',
    name_en: 'Romanian Deadlift',
    muscle_primary: 'Ноги',
    muscle_emoji: '🦵',
    is_compound: true,
    increment_kg: 2.5,
    tempo: '3-1-2',
    workout_slot: 'B',
    exercise_order: 3,
    tips_ru: 'Штанга близко к голеням. Отводи таз назад — не сгибай колени сильно. Почувствуй растяжение бицепса бедра — стоп.',
    sets: 3,
    reps: '10-12',
    instagramUrl: 'https://www.instagram.com/reel/DVeTnK8kqOm/',
    alternatives: ['https://www.instagram.com/reel/DVY01e-gU4u/'],
  },
  {
    id: 'leg_press',
    name_ru: 'Жим ногами',
    name_en: 'Leg Press',
    muscle_primary: 'Ноги',
    muscle_emoji: '🦵',
    is_compound: true,
    increment_kg: 5,
    tempo: '3-1-2',
    workout_slot: 'B',
    exercise_order: 4,
    tips_ru: 'Стопы на ширине плеч, средняя часть платформы. Опускай до 90° в колене — не ниже. Не отрывай поясницу от спинки.',
    sets: 3,
    reps: '10-15',
    instagramUrl: 'https://www.instagram.com/reel/DV4mQyviG46/',
    alternatives: [],
  },
  {
    id: 'dips',
    name_ru: 'Отжимания на брусьях',
    name_en: 'Dips',
    muscle_primary: 'Трицепс',
    muscle_emoji: '🔱',
    is_compound: true,
    increment_kg: 0,
    tempo: '2-1-2',
    workout_slot: 'B',
    exercise_order: 5,
    tips_ru: 'Держись прямо для акцента на трицепс. Опускайся до 90° в локте. Не раскачивайся. Сожми трицепс в верхней точке.',
    sets: 3,
    reps: '8-15',
    instagramUrl: 'https://www.instagram.com/reel/DVq4dqWlJih/',
    alternatives: ['https://www.instagram.com/reel/DUOJeV7D8dh/'],
  },
  {
    id: 'triceps_pushdown',
    name_ru: 'Жим верхнего блока на трицепс',
    name_en: 'Triceps Pushdown',
    muscle_primary: 'Трицепс',
    muscle_emoji: '🔱',
    is_compound: false,
    increment_kg: 1,
    tempo: '2-1-2',
    workout_slot: 'B',
    exercise_order: 6,
    tips_ru: 'Локти прижаты к телу — не двигаются. Жми до полного разгибания. Контролируй возврат. Не используй вес тела.',
    sets: 3,
    reps: '12-15',
    instagramUrl: 'https://www.instagram.com/reel/DV16kaxDeQ1/',
    alternatives: [
      'https://www.instagram.com/reel/DVpdud0kXp4/',
      'https://www.instagram.com/reel/DVKV7KQGCB8/',
    ],
  },
]
