import { Exercise } from '../../types'

export const EXERCISES_B: Exercise[] = [
  {
    id: 'military_press',
    name_ru: 'Армейский жим',
    name_en: 'Military Press',
    muscle_primary: 'Плечи',
    muscle_emoji: '🎯',
    is_compound: true,
    increment_kg: 2,
    tempo: '2-1-2',
    workout_slot: 'B',
    exercise_order: 1,
    tips_ru: 'Развитие общей мощности торса. Держите пресс напряжённым, чтобы не прогибать поясницу.',
    sets: 3,
    reps: '8-10',
    instagramUrl: 'https://www.youtube.com/shorts/E7ngsffMPR0',
    alternatives: ['https://www.youtube.com/watch?v=4LBVP2Oe7fg'],
  },
  {
    id: 'dumbbell_row',
    name_ru: 'Тяга гантели к поясу',
    name_en: 'Dumbbell Row',
    muscle_primary: 'Спина',
    muscle_emoji: '🔝',
    is_compound: true,
    increment_kg: 2,
    tempo: '2-1-3',
    workout_slot: 'B',
    exercise_order: 2,
    tips_ru: 'Фокус на локте — ведите его к бедру, а не к груди, чтобы исключить бицепс.',
    sets: 4,
    reps: '10-12',
    instagramUrl: 'https://www.youtube.com/shorts/q8E9XaizZpY',
    alternatives: ['https://www.youtube.com/watch?v=WkFX6_GxAs8'],
  },
  {
    id: 'rdl',
    name_ru: 'Румынская тяга (RDL)',
    name_en: 'Romanian Deadlift',
    muscle_primary: 'Ноги',
    muscle_emoji: '🦵',
    is_compound: true,
    increment_kg: 2.5,
    tempo: '3-1-2',
    workout_slot: 'B',
    exercise_order: 3,
    tips_ru: 'Опускайте до середины голени, чувствуя растяжение задней поверхности бедра.',
    sets: 3,
    reps: '10-12',
    instagramUrl: 'https://www.youtube.com/shorts/hu3jRvTc_po',
    alternatives: ['https://www.youtube.com/watch?v=Wou9zVQrAfs'],
  },
  {
    id: 'dips',
    name_ru: 'Отжимания на брусьях (на трицепс)',
    name_en: 'Tricep Dips',
    muscle_primary: 'Трицепс',
    muscle_emoji: '🔱',
    is_compound: true,
    increment_kg: 0,
    tempo: '2-1-2',
    workout_slot: 'B',
    exercise_order: 4,
    tips_ru: 'Держите корпус вертикально, локти близко к телу — акцент на трицепс.',
    sets: 3,
    reps: '10-12',
    instagramUrl: 'https://www.youtube.com/shorts/WjLJ7zIppXQ',
    alternatives: ['https://www.youtube.com/watch?v=eicOUO9WaJc'],
  },
  {
    id: 'hammer_curl',
    name_ru: 'Молотковые сгибания',
    name_en: 'Hammer Curl',
    muscle_primary: 'Бицепс',
    muscle_emoji: '💪',
    is_compound: false,
    increment_kg: 1,
    tempo: '2-1-3',
    workout_slot: 'B',
    exercise_order: 5,
    tips_ru: 'Строят брахиалис, который «выталкивает» бицепс, делая руку толще.',
    sets: 3,
    reps: '12',
    instagramUrl: 'https://www.youtube.com/watch?v=fc10K1s6fLE',
    alternatives: ['https://www.youtube.com/watch?v=_aoad2yuP5w'],
  },
  {
    id: 'leg_raise',
    name_ru: 'Подъём ног в висе',
    name_en: 'Hanging Leg Raise',
    muscle_primary: 'Пресс',
    muscle_emoji: '🔥',
    is_compound: false,
    increment_kg: 0,
    tempo: '2-1-3',
    workout_slot: 'B',
    exercise_order: 6,
    tips_ru: 'Для прорисовки нижнего пресса при дефиците калорий. Не раскачивайся — контролируй движение.',
    sets: 3,
    reps: '15-20',
    instagramUrl: 'https://www.youtube.com/watch?v=aP4HfrLkOLU',
    alternatives: [],
  },
]
