import { Exercise } from '../../types'

export const EXERCISES_C: Exercise[] = [
  {
    id: 'low_to_high_cable',
    name_ru: 'Тяга блоков снизу вверх',
    name_en: 'Low-to-High Cable Fly',
    muscle_primary: 'Грудь',
    muscle_emoji: '🏋️',
    is_compound: false,
    increment_kg: 1,
    tempo: '2-1-2',
    workout_slot: 'C',
    exercise_order: 1,
    tips_ru: 'Изолирующая «дошлифовка» верхней части грудных мышц.',
    sets: 3,
    reps: '12-15',
    instagramUrl: 'https://www.youtube.com/watch?v=ZVwgKeqrYeA',
    alternatives: ['https://www.youtube.com/watch?v=AJhU25QU7A0', 'https://www.youtube.com/shorts/4-258XRGL2g'],
  },
  {
    id: 'lat_pulldown',
    name_ru: 'Тяга верхнего блока широким хватом',
    name_en: 'Wide-Grip Lat Pulldown',
    muscle_primary: 'Спина',
    muscle_emoji: '🔝',
    is_compound: true,
    increment_kg: 2,
    tempo: '2-1-3',
    workout_slot: 'C',
    exercise_order: 2,
    tips_ru: 'Концентрируйтесь на опускании лопаток в нижней точке.',
    sets: 3,
    reps: '12',
    instagramUrl: 'https://www.youtube.com/watch?v=bNmvKpJSWKM',
    alternatives: ['https://www.youtube.com/shorts/RFgiCDJs8Nk', 'https://www.youtube.com/shorts/wUywhht3YBQ'],
  },
  {
    id: 'upright_row',
    name_ru: 'Тяга штанги к подбородку (широкая)',
    name_en: 'Wide-Grip Upright Row',
    muscle_primary: 'Плечи',
    muscle_emoji: '🎯',
    is_compound: true,
    increment_kg: 1,
    tempo: '2-1-2',
    workout_slot: 'C',
    exercise_order: 3,
    tips_ru: 'Используйте широкий хват, чтобы направить нагрузку на среднюю дельту, а не на трапеции.',
    sets: 3,
    reps: '12-15',
    instagramUrl: 'https://www.youtube.com/watch?v=IYfLFuGKFLI',
    alternatives: [],
  },
  {
    id: 'rear_delt_fly',
    name_ru: 'Разведения на заднюю дельту',
    name_en: 'Rear Delt Fly',
    muscle_primary: 'Плечи',
    muscle_emoji: '🎯',
    is_compound: false,
    increment_kg: 1,
    tempo: '2-1-3',
    workout_slot: 'C',
    exercise_order: 4,
    tips_ru: 'Придает плечам завершенную 3D-форму.',
    sets: 3,
    reps: '15-20',
    instagramUrl: 'https://www.youtube.com/watch?v=FeERX9UwspY',
    alternatives: ['https://www.youtube.com/watch?v=cGXBVOc5xIk', 'https://www.youtube.com/shorts/JlT2xB92lY8'],
  },
  {
    id: 'squat',
    name_ru: 'Приседания со штангой',
    name_en: 'Barbell Squat',
    muscle_primary: 'Ноги',
    muscle_emoji: '🦵',
    is_compound: true,
    increment_kg: 2.5,
    tempo: '3-1-2',
    workout_slot: 'C',
    exercise_order: 5,
    tips_ru: 'Метаболический локомотив тренировки. Следите за глубиной — бедро параллельно полу.',
    sets: 3,
    reps: '10-12',
    instagramUrl: 'https://www.youtube.com/watch?v=dW3zj79xfrc',
    alternatives: [],
  },
  {
    id: 'cable_tricep_pushdown',
    name_ru: 'Разгибания на трицепс (канат)',
    name_en: 'Cable Tricep Pushdown',
    muscle_primary: 'Трицепс',
    muscle_emoji: '🔱',
    is_compound: false,
    increment_kg: 1,
    tempo: '2-1-2',
    workout_slot: 'C',
    exercise_order: 6,
    tips_ru: 'В нижней точке разводите руки в стороны для пикового сокращения.',
    sets: 3,
    reps: '12-15',
    instagramUrl: 'https://www.youtube.com/watch?v=1FjkhpZsaxc',
    alternatives: [],
  },
]
