import { Exercise } from '../../types'

export const EXERCISES_A: Exercise[] = [
  {
    id: 'incline_dumbbell_press',
    name_ru: 'Жим гантелей на наклонной',
    name_en: 'Incline Dumbbell Press',
    muscle_primary: 'Грудь',
    muscle_emoji: '💪',
    is_compound: true,
    increment_kg: 2,
    tempo: '3-1-2',
    workout_slot: 'A',
    exercise_order: 1,
    tips_ru: 'Угол скамьи 30–45°. Лопатки сведены и прижаты. Опускай медленно 3 сек, жми через пятки ладоней.',
    sets: 3,
    reps: '8-12',
    instagramUrl: 'https://www.instagram.com/reel/DVTlN1AEQZH/',
    alternatives: ['https://www.instagram.com/reel/DVd3338ASdO/'],
  },
  {
    id: 'pull_ups',
    name_ru: 'Подтягивания',
    name_en: 'Pull-ups',
    muscle_primary: 'Спина',
    muscle_emoji: '🔝',
    is_compound: true,
    increment_kg: 0,
    tempo: '2-1-3',
    workout_slot: 'A',
    exercise_order: 2,
    tips_ru: 'Хват чуть шире плеч. Тяни лопатки вниз до начала движения. Полное разгибание внизу — обязательно.',
    sets: 3,
    reps: '6-12',
    instagramUrl: 'https://www.instagram.com/reel/DVYLCDoj6G5/',
    alternatives: [],
  },
  {
    id: 'cable_lateral_raise',
    name_ru: 'Разведения в кроссовере',
    name_en: 'Cable Lateral Raise',
    muscle_primary: 'Плечи',
    muscle_emoji: '🎯',
    is_compound: false,
    increment_kg: 1,
    tempo: '2-1-2',
    workout_slot: 'A',
    exercise_order: 3,
    tips_ru: 'Кабель снизу, рука слегка согнута. Веди локоть, не кисть. Стоп в точке параллели с полом — не выше.',
    sets: 3,
    reps: '12-20',
    instagramUrl: 'https://www.instagram.com/reel/DVhbejJje7f/',
    alternatives: [
      'https://www.instagram.com/reel/DVL-XDUk9cl/',
      'https://www.instagram.com/reel/DUUEdhkFNEv/',
    ],
  },
  {
    id: 'hip_thrust',
    name_ru: 'Ягодичный мост (Хип-траст)',
    name_en: 'Hip Thrust',
    muscle_primary: 'Ягодицы',
    muscle_emoji: '🍑',
    is_compound: true,
    increment_kg: 5,
    tempo: '2-1-2',
    workout_slot: 'A',
    exercise_order: 4,
    tips_ru: 'Лопатки на скамье, штанга на тазобедренных. Сожми ягодицы в верхней точке, держи 1 сек. Не перегибай поясницу.',
    sets: 3,
    reps: '10-15',
    instagramUrl: 'https://www.instagram.com/reel/DVH3cAcjdNf/',
    alternatives: [],
  },
  {
    id: 'squat',
    name_ru: 'Приседания',
    name_en: 'Squat',
    muscle_primary: 'Ноги',
    muscle_emoji: '🦵',
    is_compound: true,
    increment_kg: 2.5,
    tempo: '3-1-2',
    workout_slot: 'A',
    exercise_order: 5,
    tips_ru: 'Стопы на ширине плеч, носки чуть врозь. Спина нейтральная. Колени над носками. Садись до параллели или ниже.',
    sets: 3,
    reps: '8-12',
    instagramUrl: 'https://www.instagram.com/reel/DTqZMvSEqyD/',
    alternatives: [
      'https://www.instagram.com/reel/DUWzspwDenA/',
      'https://www.instagram.com/reel/DV_IXcCAkWT/',
    ],
  },
  {
    id: 'biceps_curl',
    name_ru: 'Сгибания на бицепс (EZ-гриф)',
    name_en: 'Biceps Curl',
    muscle_primary: 'Бицепс',
    muscle_emoji: '💪',
    is_compound: false,
    increment_kg: 1,
    tempo: '2-1-3',
    workout_slot: 'A',
    exercise_order: 6,
    tips_ru: 'Локти прижаты к телу — не двигаются. Полное разгибание внизу. Сожми бицепс наверху. Не раскачивайся.',
    sets: 3,
    reps: '10-15',
    instagramUrl: 'https://www.instagram.com/reel/DVoSXnnCVQd/',
    alternatives: [
      'https://www.instagram.com/reel/DVjPOfeCG7p/',
      'https://www.instagram.com/reel/DU0o3WbkzTA/',
    ],
  },
]
